### ISSUE TITLE
No ES6 support

### ISSUE THREAD

**Issue by skeate** [bigfish/vim-js-context-coloring#17]

**Comment by bigfish** [comment]
Hi, thanks for bringing this up, I've been pondering how to support ES6. I can probably lean on the Acorn parser to support this without much difficulty, so I try and do that soon. I'm just not sure about colorizing block scopes, but that would be a neat thing to get working... it will depend on the parser support.

**Comment by bigfish** [comment]
I've added ES6 support by default in latest version.  See the updated readme for more details...
Let me know if you experience any issues with ES6. There are new packages required, so do an update or reinstall, and then 'npm install'.

**Comment by bigfish** [comment]
Ok, I've done a fair amount of testing and will continue to do so as I start working more with ES6, but ES6 is now supported, so I'll close this issue. If there are any specific ES6 syntax features that are causing trouble, just open another issue for that.

**Comment by skeate** [comment]
Awesome! Thank you!
