### ISSUE TITLE
Compatibility with JSX

### ISSUE THREAD

**Issue by gunar** [bigfish/vim-js-context-coloring#20]
Toggling Context Coloring on and off (to switch to other syntax highlighters) is awesome. It's just very unfortunate that having JSContextColoring installed breaks [mxw/vim-jsx](https://github.com/mxw/vim-jsx).

Are there other options for JSX, or how could this be fixed?

Thank you.

**Comment by bigfish** [comment]
I also use vim-jsx, and it works when I toggle the context-coloring off ..  you would like to have vim-jsx highlighting while the context-coloring is on? Or is it not working at all for you?

**Comment by bigfish** [comment]
I have added a new option to allow vim-jsx syntax to override the context coloring... you need to do 3 things to test it ..

1. pull master branch of this plugin
2. make sure the vim-jsx plugin is loaded AFTER this one
3. set `g:js_context_colors_allow_jsx_syntax` to 1

try loading file with jsx in it.. JSX highlighting should appear. 

I still need to update the neovim branch for this...
