### ISSUE TITLE
Error when attempting to open more than one file

### ISSUE THREAD

**Issue by faruzzy** [bigfish/vim-js-context-coloring#26]
I get an error attempting opening multiple files like when running `vim -O file1.js file2.js`

![image](https://cloud.githubusercontent.com/assets/766723/19995057/edd5dbd4-a210-11e6-9cc0-9f91d5dd2aa7.png)

**Comment by bigfish** [comment]
ok, I'll see what's up

**Comment by bigfish** [comment]
I can't reproduce this on Vim 8 on Mac OSX, or vim 7.4 on Ubuntu.. what version of vim are you using ? 

b:scope_groups is defined at the top of the script so should definitely exist.

**Comment by faruzzy** [comment]
I'm using version 7.4.2290 on Mac OSX

**Comment by bigfish** [comment]
Thanks for the pull request, however I took a slightly different approach to fix this (speculatively, since I cannot reproduce it). I suspect you may have other plugins that are somehow triggering this behaviour. Anyways, can you try pull the latest from master, and confirm that it fixes your issue?

**Comment by faruzzy** [comment]
This is got rid of the error but, now I'm getting the first file with syntax coloring and the second file with no syntax coloring.

![image](https://cloud.githubusercontent.com/assets/766723/20234305/7ed8f69a-a836-11e6-9b63-2884c2af324f.png)

**Comment by bigfish** [comment]
Hmm. I've tried with 7.4 on Mac OSX, in bash shell (iTerm2).

I only have this plugin installed (I cloned it and renamed it to ~/.vim (and ran 'npm install' in it). I have minimal .vimrc ..

set nocompatible
filetype plugin indent on
syntax on

and when I open 2 files with -O, they are both colored correctly.

I suspect you may have some interaction between plugins.. can you try with minimal setup like this, without other plugins? If it works, it must be something in your vim environment or plugins. You can add them back one by one to find the culprit.

**Comment by faruzzy** [comment]
Yeah, I now agree with you on the fact that this is a problem that is caused by something on my side. That being said, my configuration is quite big, and it would take a while to find the culprit. I think we can close this now
